#!/usr/bin/env bash
#
# cleanup-coding-env.sh — Removes all auto-generated files from coding environment setup.
#
# Resets the repo to pre-setup state by removing every file/directory that
# setup-coding-env.sh and setup-ai-rules.sh create.
#
# Usage:
#   ./cleanup-coding-env.sh           # Remove all generated artifacts
#   ./cleanup-coding-env.sh --help    # Show help
#
# Safe to run multiple times (idempotent). Missing files/dirs are silently skipped.
#
set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
GRAY='\033[0;90m'
BOLD='\033[1m'
NC='\033[0m'

info()   { echo -e "${BLUE}i${NC}  $1"; }
ok()     { echo -e "${GREEN}✓${NC}  $1"; }
skip()   { echo -e "${GRAY}-  $1${NC}"; }
header() { echo -e "\n${BOLD}═══ $1 ═══${NC}\n"; }

# --- Helpers ------------------------------------------------------------------
remove_file() {
  local path="$1"
  local label="$2"
  if [ -f "$path" ] || [ -L "$path" ]; then
    rm -f "$path"
    ok "removed: $label"
  else
    skip "absent:  $label"
  fi
}

remove_dir() {
  local path="$1"
  local label="$2"
  if [ -d "$path" ]; then
    rm -rf "$path"
    ok "removed: $label"
  else
    skip "absent:  $label"
  fi
}

# ==============================================================================
# Main
# ==============================================================================

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  echo "Usage: $0"
  echo ""
  echo "Removes all files and directories generated by setup-coding-env.sh"
  echo "and setup-ai-rules.sh. Safe to run multiple times."
  echo ""
  echo "Removes:"
  echo "  Files : .clinerules, .continuerules, .cursorrules, .windsurfrules,"
  echo "          AGENTS.md, CLAUDE.md, skills-lock.json,"
  echo "          .github/copilot-instructions.md"
  echo "  Dirs  : .codegraph/, .agents/, .continue/, .roo/"
  exit 0
fi

PROJECT_DIR="$(pwd)"

echo -e "${BOLD}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║        Coding Environment Cleanup                            ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"
info "Project: $PROJECT_DIR"

# Prompt the user alerting them what folders / files will be auto removed, if they decline just exit
echo "The following files and directories will be removed:"
echo "  Files : .clinerules, .continuerules, .cursorrules, .windsurfrules,"
echo "          AGENTS.md, CLAUDE.md, skills-lock.json,"
echo "          .github/copilot-instructions.md"
echo "  Dirs  : .codegraph/, .agents/, .continue/, .roo/"
read -p "Do you want to continue? [y/N] " response
if [[ ! "$response" =~ ^[Yy]$ ]]; then
  echo "Cleanup aborted."
  exit 0
fi

# --- Generated files (root) ---------------------------------------------------
header "Generated Files"

remove_file "$PROJECT_DIR/.clinerules"                        ".clinerules"
remove_file "$PROJECT_DIR/.continuerules"                     ".continuerules"
remove_file "$PROJECT_DIR/.cursorrules"                       ".cursorrules"
remove_file "$PROJECT_DIR/.windsurfrules"                     ".windsurfrules"
remove_file "$PROJECT_DIR/AGENTS.md"                          "AGENTS.md"
remove_file "$PROJECT_DIR/CLAUDE.md"                          "CLAUDE.md"
remove_file "$PROJECT_DIR/skills-lock.json"                   "skills-lock.json"
remove_file "$PROJECT_DIR/.github/copilot-instructions.md"    ".github/copilot-instructions.md"

# --- Generated directories (root) ---------------------------------------------
header "Generated Directories"

remove_dir "$PROJECT_DIR/.codegraph"  ".codegraph/"
remove_dir "$PROJECT_DIR/.agents"     ".agents/"
remove_dir "$PROJECT_DIR/.continue"   ".continue/"
remove_dir "$PROJECT_DIR/.roo"        ".roo/"

# ------------------------------------------------------------------------------
echo ""
ok "Cleanup complete. Repo reset to pre-setup state."
echo ""
