#
# cleanup-coding-env.ps1 — Removes all auto-generated files from coding environment setup.
#
# Resets the repo to pre-setup state by removing every file/directory that
# setup-coding-env.ps1 and setup-ai-rules.ps1 create.
#
# Usage:
#   .\cleanup-coding-env.ps1           # Remove all generated artifacts
#   .\cleanup-coding-env.ps1 -Help     # Show help
#
# Safe to run multiple times (idempotent). Missing files/dirs are silently skipped.
#

param(
    [switch]$Help
)

$ErrorActionPreference = "Stop"

# --- Colors -------------------------------------------------------------------
function Write-Info   { param([string]$Msg) Write-Host "i  $Msg" -ForegroundColor Blue }
function Write-Ok     { param([string]$Msg) Write-Host ([char]0x2713 + "  $Msg") -ForegroundColor Green }
function Write-Warn   { param([string]$Msg) Write-Host ([char]0x26A0 + "  $Msg") -ForegroundColor Yellow }
function Write-Skip   { param([string]$Msg) Write-Host "-  $Msg" -ForegroundColor DarkGray }
function Write-Header { param([string]$Msg) Write-Host ("`n" + [char]0x2550 + [char]0x2550 + [char]0x2550 + " $Msg " + [char]0x2550 + [char]0x2550 + [char]0x2550 + "`n") -ForegroundColor White }

# --- Helpers ------------------------------------------------------------------
function Remove-GeneratedFile {
    param([string]$Path, [string]$Label)
    if (Test-Path $Path) {
        Remove-Item $Path -Force
        Write-Ok "removed: $Label"
    } else {
        Write-Skip "absent:  $Label"
    }
}

function Remove-GeneratedDir {
    param([string]$Path, [string]$Label)
    if (Test-Path $Path) {
        Remove-Item $Path -Recurse -Force
        Write-Ok "removed: $Label"
    } else {
        Write-Skip "absent:  $Label"
    }
}

# ==============================================================================
# Main
# ==============================================================================

if ($Help) {
    Write-Host "Usage: .\cleanup-coding-env.ps1"
    Write-Host ""
    Write-Host "Removes all files and directories generated by setup-coding-env.ps1"
    Write-Host "and setup-ai-rules.ps1. Safe to run multiple times."
    Write-Host ""
    Write-Host "Removes:"
    Write-Host "  Files : .clinerules, .continuerules, .cursorrules, .windsurfrules,"
    Write-Host "          AGENTS.md, CLAUDE.md, skills-lock.json,"
    Write-Host "          .github\copilot-instructions.md"
    Write-Host "  Dirs  : .codegraph\, .agents\, .continue\, .roo\"
    exit 0
}

$ProjectDir = Get-Location

Write-Host ""
Write-Host ([char]0x2554 + ([string][char]0x2550 * 63) + [char]0x2557) -ForegroundColor White
Write-Host ([char]0x2551 + "        Coding Environment Cleanup                            " + [char]0x2551) -ForegroundColor White
Write-Host ([char]0x255A + ([string][char]0x2550 * 63) + [char]0x255D) -ForegroundColor White
Write-Host ""
Write-Info "Project: $ProjectDir"
Write-Host ""
Write-Host "WARNING: THIS WILL REMOVE ALL RULE FILES AND GENERATED DIRECTORIES. PROCEED WITH CAUTION."
Write-Host ""

# Prompt the user if they wish to proceed
$proceed = Read-Host "?  Do you wish to proceed? [y/N]"
if ($proceed -notmatch '^[Yy]$') {
    Write-Host "Aborted by user."
    exit 0
}

# --- Generated files (root) ---------------------------------------------------
Write-Header "Generated Files"

Remove-GeneratedFile (Join-Path $ProjectDir ".clinerules")               ".clinerules"
Remove-GeneratedFile (Join-Path $ProjectDir ".continuerules")            ".continuerules"
Remove-GeneratedFile (Join-Path $ProjectDir ".cursorrules")              ".cursorrules"
Remove-GeneratedFile (Join-Path $ProjectDir ".windsurfrules")            ".windsurfrules"
Remove-GeneratedFile (Join-Path $ProjectDir "AGENTS.md")                 "AGENTS.md"
Remove-GeneratedFile (Join-Path $ProjectDir "CLAUDE.md")                 "CLAUDE.md"
Remove-GeneratedFile (Join-Path $ProjectDir "skills-lock.json")          "skills-lock.json"
Remove-GeneratedFile (Join-Path $ProjectDir ".github\copilot-instructions.md") ".github\copilot-instructions.md"

# --- Generated directories (root) ---------------------------------------------
Write-Header "Generated Directories"

Remove-GeneratedDir (Join-Path $ProjectDir ".codegraph") ".codegraph\"
Remove-GeneratedDir (Join-Path $ProjectDir ".agents")    ".agents\"
Remove-GeneratedDir (Join-Path $ProjectDir ".continue")  ".continue\"
Remove-GeneratedDir (Join-Path $ProjectDir ".roo")       ".roo\"

# ------------------------------------------------------------------------------
Write-Host ""
Write-Ok "Cleanup complete. Repo reset to pre-setup state."
Write-Host ""
